spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/proxy-loop
server:
  port: 8081
logging:
  level:
    com.visionki.pixiv: debug
    org.apache.http: info
    org .springframework.data.mongodb.core: info